<?php

use App\Argo\Project;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Config;

class TestProjectSeeder extends Seeder
{
    public function run()
    {
        $records = array(
            //-- Schools ---------------------------------------------------------------------------------------------------------------------
            array(
                'id' => 1,
                'group_id' => 1,
                'title' => 'Hogwarts Senior High School',
                'lat' => 5.9835,
                'lng' => -9.3082,
                'description' => "Qolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas.",
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'default_img_id' => 5,
                'cover_image_id' => 4,
                'default_form_id' => 1,
                'container_id' => 1,
                'created_by' => 1,
            ),
            array(
                'id' => 2,
                'group_id' => 1,
                'title' => 'Beauxbatons Senior High School',
                'lat' => 6.0088,
                'lng' => -9.7806,
                'description' => 'vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere',
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'default_img_id' => 6,
                'cover_image_id' => null,
                'default_form_id' => 1,
                'container_id' => 1,
                'created_by' => 1,
            ),
            array(
                'id' => 3,
                'group_id' => 1,
                'title' => 'Gryffindor Junior High School',
                'lat' => 6.2020,
                'lng' => -9.8108,
                'description' => 'Dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui.',
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'default_img_id' => 7,
                'cover_image_id' => 11,
                'default_form_id' => 1,
                'container_id' => 1,
                'created_by' => 1,
            ),
            array(
                'id' => 4,
                'group_id' => 1,
                'title' => 'Hufflepuff Junior High School',
                'lat' => 6.5828,
                'lng' => -10.0731,
                'description' => 'Illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam',
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'default_img_id' => 8,
                'cover_image_id' => 12,
                'default_form_id' => 1,
                'container_id' => 1,
                'created_by' => 1,
            ),
            array(
                'id' => 5,
                'group_id' => 1,
                'title' => 'Slytherin Junior High School',
                'lat' => 7.4803,
                'lng' => -10.4054,
                'description' => 'unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.',
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'default_img_id' => 9,
                'cover_image_id' => 14,
                'default_form_id' => 1,
                'container_id' => 1,
                'created_by' => 1,
            ),
            array(
                'id' => 6,
                'group_id' => 1,
                'title' => 'Ravenclaw Junior High School',
                'lat' => 5.7933,
                'lng' => -8.3300,
                'description' => 'Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue.',
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'default_img_id' => 10,
                'cover_image_id' => 13,
                'default_form_id' => 1,
                'container_id' => 1,
                'created_by' => 1,
            ),
            //-- Roads -----------------------------------------------------------------------------------------------------------------------
            array(
                'id' => 7,
                'group_id' => 1,
                'title' => 'Sample Road 1',
                'lat' => 6.31043,
                'lng' => -10.80492,
                'description' => 'Speed vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.',
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'cover_image_id' => 16,
                'default_form_id' => 1,
                'container_id' => 2,
                'created_by' => 1,
            ),
            array(
                'id' => 8,
                'group_id' => 1,
                'title' => 'Sample Road 2',
                'lat' => 6.31036,
                'lng' => -10.80698,
                'description' => 'Speed Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat.',
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'cover_image_id' => 17,
                'default_form_id' => 1,
                'container_id' => 2,
                'created_by' => 1,
            ),
            array(
                'id' => 9,
                'group_id' => 1,
                'title' => 'Sample Road 3',
                'lat' => 7.19567624916161,
                'lng' => -8.43558461099932,
                'description' => 'IRI Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel.',
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'cover_image_id' => 18,
                'default_form_id' => 1,
                'container_id' => 2,
                'created_by' => 1,
            ),
            //-- Studnets --------------------------------------------------------------------------------------------------------------------
            array(
                'id' => 10,
                'group_id' => 1,
                'title' => 'Student 1',
                'lat' => null,
                'lng' => null,
                'description' => 'Aet ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus',
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'default_form_id' => 1,
                'parent_id' => 1,
                'container_id' => 8,
                'created_by' => 1,
            ),
            array(
                'id' => 11,
                'group_id' => 1,
                'title' => 'Student 2',
                'lat' => null,
                'lng' => null,
                'description' => 'Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc.',
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'default_form_id' => 1,
                'parent_id' => 1,
                'container_id' => 8,
                'created_by' => 1,
            ),
            array(
                'id' => 12,
                'group_id' => 1,
                'title' => 'Student 3',
                'lat' => null,
                'lng' => null,
                'description' => 'Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel.',
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'default_form_id' => 1,
                'parent_id' => 1,
                'container_id' => 8,
                'created_by' => 1,
            ),
            array(
                'id' => 13,
                'group_id' => 1,
                'title' => 'Student 4',
                'lat' => null,
                'lng' => null,
                'description' => 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur.',
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'default_form_id' => 1,
                'parent_id' => 1,
                'container_id' => 8,
                'created_by' => 1,
            ),
            array(
                'id' => 14,
                'group_id' => 1,
                'title' => 'Student 5',
                'lat' => null,
                'lng' => null,
                'description' => 'Nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.',
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'default_form_id' => 1,
                'parent_id' => 5,
                'container_id' => 8,
                'created_by' => 1,
            ),

            array(
                'id' => 15,
                'group_id' => 1,
                'title' => 'Student 6',
                'lat' => null,
                'lng' => null,
                'description' => 'Aet ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus',
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'default_form_id' => 1,
                'parent_id' => 2,
                'container_id' => 8,
                'created_by' => 1,
            ),
            array(
                'id' => 16,
                'group_id' => 1,
                'title' => 'Student 7',
                'lat' => null,
                'lng' => null,
                'description' => 'Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc.',
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'default_form_id' => 1,
                'parent_id' => 2,
                'container_id' => 8,
                'created_by' => 1,
            ),
            array(
                'id' => 17,
                'group_id' => 1,
                'title' => 'Student 8',
                'lat' => null,
                'lng' => null,
                'description' => 'Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel.',
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'default_form_id' => 1,
                'parent_id' => 4,
                'container_id' => 8,
                'created_by' => 1,
            ),
            array(
                'id' => 18,
                'group_id' => 1,
                'title' => 'Student 9',
                'lat' => null,
                'lng' => null,
                'description' => 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur.',
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'default_form_id' => 1,
                'parent_id' => 4,
                'container_id' => 8,
                'created_by' => 1,
            ),
            array(
                'id' => 19,
                'group_id' => 1,
                'title' => 'Student 10',
                'lat' => null,
                'lng' => null,
                'description' => 'Nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.',
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'default_form_id' => 1,
                'parent_id' => 6,
                'container_id' => 8,
                'created_by' => 1,
            ),

            //-- Unit Test Project
            array(
                'id' => 20,
                'group_id' => 1,
                'title' => 'Unit Test Project Title',
                'lat' => null,
                'lng' => null,
                'description' => 'Unit Test Project Description',
                'view_level_id' => Config::get('argodf.default_perm.project.view'),
                'edit_level_id' => 2,
                'default_form_id' => 13,
                'parent_id' => null,
                'container_id' => 1,
                'created_by' => 1,
            ),
        );

        $this->command->info("Project : Seeding " . count($records) . " records...");
        foreach ($records as $record) {
            Project::create($record);
        }
    }
}
