<?php
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class TestReportSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();
        $records = array(
            array('id' => 1,
                'project_id' => 1,
                'description' => 'Hogwarts Report 1',
                'view_level_id' => config('argodf.default_perm.report.view'),
                'edit_level_id' => config('argodf.default_perm.report.edit'),
                'created_by' => 1,
                'created_at' => Carbon::now()->subYear(7),
                'updated_at' => Carbon::now()->subYear(7)),
            array('id' => 2,
                'project_id' => 1,
                'description' => 'Hogwarts Report 2',
                'view_level_id' => config('argodf.default_perm.report.view'),
                'edit_level_id' => config('argodf.default_perm.report.edit'),
                'created_by' => 1,
                'created_at' => Carbon::now()->subYear(6),
                'updated_at' => Carbon::now()->subYear(6)),
            array('id' => 3,
                'project_id' => 1,
                'description' => 'Hogwarts Report 3',
                'view_level_id' => config('argodf.default_perm.report.view'),
                'edit_level_id' => config('argodf.default_perm.report.edit'),
                'created_by' => 1,
                'created_at' => Carbon::now()->subYear(5),
                'updated_at' => Carbon::now()->subYear(5)),
            array('id' => 4,
                'project_id' => 1,
                'description' => 'Hogwarts Report 4',
                'view_level_id' => config('argodf.default_perm.report.view'),
                'edit_level_id' => config('argodf.default_perm.report.edit'),
                'created_by' => 1,
                'created_at' => Carbon::now()->subYear(4),
                'updated_at' => Carbon::now()->subYear(4)),
            array('id' => 5,
                'project_id' => 1,
                'description' => 'Hogwarts Report 5',
                'view_level_id' => config('argodf.default_perm.report.view'),
                'edit_level_id' => config('argodf.default_perm.report.edit'),
                'created_by' => 1,
                'created_at' => Carbon::now()->subYears(3),
                'updated_at' => Carbon::now()->subYears(3)),
            array('id' => 6,
                'project_id' => 1,
                'description' => 'Hogwarts Report 6',
                'view_level_id' => config('argodf.default_perm.report.view'),
                'edit_level_id' => config('argodf.default_perm.report.edit'),
                'created_by' => 1,
                'created_at' => Carbon::now()->subYears(2),
                'updated_at' => Carbon::now()->subYears(2)),
            array('id' => 7,
                'project_id' => 1,
                'description' => 'Hogwarts Report 7',
                'view_level_id' => config('argodf.default_perm.report.view'),
                'edit_level_id' => config('argodf.default_perm.report.edit'),
                'created_by' => 1,
                'created_at' => Carbon::now()->subYear(),
                'updated_at' => Carbon::now()->subYear()),
            array('id' => 8,
                'project_id' => 1,
                'description' => 'Hogwarts Report 8',
                'view_level_id' => config('argodf.default_perm.report.view'),
                'edit_level_id' => config('argodf.default_perm.report.edit'),
                'created_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()),
            array('id' => 9,
                'project_id' => 1,
                'description' => 'Hogwarts Report 9',
                'view_level_id' => config('argodf.default_perm.report.view'),
                'edit_level_id' => config('argodf.default_perm.report.edit'),
                'created_by' => 1,
                'created_at' => Carbon::now()->subMonths(7),
                'updated_at' => Carbon::now()->subMonths(7)),
            array('id' => 10,
                'project_id' => 1,
                'description' => 'Hogwarts Report 10',
                'view_level_id' => config('argodf.default_perm.report.view'),
                'edit_level_id' => config('argodf.default_perm.report.edit'),
                'created_by' => 1,
                'created_at' => Carbon::now()->subMonths(6),
                'updated_at' => Carbon::now()->subMonths(6)),
            array('id' => 11,
                'project_id' => 1,
                'description' => 'Hogwarts Report 11',
                'view_level_id' => config('argodf.default_perm.report.view'),
                'edit_level_id' => config('argodf.default_perm.report.edit'),
                'created_by' => 1,
                'created_at' => Carbon::now()->subMonths(5),
                'updated_at' => Carbon::now()->subMonths(5)),
            array('id' => 12,
                'project_id' => 1,
                'description' => 'Hogwarts Report 12',
                'view_level_id' => config('argodf.default_perm.report.view'),
                'edit_level_id' => config('argodf.default_perm.report.edit'),
                'created_by' => 1,
                'created_at' => Carbon::now()->subMonths(4),
                'updated_at' => Carbon::now()->subMonths(4)),
            array('id' => 13,
                'project_id' => 1,
                'description' => 'Hogwarts Report 13',
                'view_level_id' => config('argodf.default_perm.report.view'),
                'edit_level_id' => config('argodf.default_perm.report.edit'),
                'created_by' => 1,
                'created_at' => Carbon::now()->subMonths(3),
                'updated_at' => Carbon::now()->subMonths(3)),
            array('id' => 14,
                'project_id' => 1,
                'description' => 'Hogwarts Report 14',
                'view_level_id' => config('argodf.default_perm.report.view'),
                'edit_level_id' => config('argodf.default_perm.report.edit'),
                'created_by' => 1,
                'created_at' => Carbon::now()->subMonths(2),
                'updated_at' => Carbon::now()->subMonths(2)),
            array('id' => 15,
                'project_id' => 1,
                'description' => 'Hogwarts Report 15',
                'view_level_id' => config('argodf.default_perm.report.view'),
                'edit_level_id' => config('argodf.default_perm.report.edit'),
                'created_by' => 1,
                'created_at' => Carbon::now()->subMonth(),
                'updated_at' => Carbon::now()->subMonth()),
            array('id' => 16,
                'project_id' => 1,
                'description' => 'Hogwarts Report 16',
                'view_level_id' => config('argodf.default_perm.report.view'),
                'edit_level_id' => config('argodf.default_perm.report.edit'),
                'created_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()),
        );
        $this->command->info("Report : Seeding " . count($records) . " records...");

        DB::table('report')->insert($records);
    }
}
