<?php
use Illuminate\Database\Seeder;
use App\Argo\FormField;
use Illuminate\Support\Facades\Config;

class TestFormFieldSeeder extends Seeder
{
     public function run()
     {
          $records = array(
               array(
                    'id' => 1,
                    'name' => "School Name",
                    'form_id' => 1,
                    'field_template_id' => 1,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 1),
               array(
                    'id' => 2,
                    'name' => "Year of Establishment",
                    'form_id' => 1,
                    'field_template_id' => 6,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 2),
               array(
                    'id' => 3,
                    'name' => "Name of Head",
                    'form_id' => 1,
                    'field_template_id' => 1,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 3),
               array(
                    'id' => 4,
                    'name' => "No. of Teachers",
                    'form_id' => 1,
                    'field_template_id' => 6,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 4),
               array(
                    'id' => 5,
                    'name' => "No. of Trained Teachers",
                    'form_id' => 1,
                    'field_template_id' => 6,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 5),

               array(
                    'id' => 6,
                    'name' => "Road Number",
                    'form_id' => 2,
                    'field_template_id' => 1,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 1),
               array(
                    'id' => 7,
                    'name' => "Length of operation",
                    'form_id' => 2,
                    'field_template_id' => 5,
                    'options' => '["1 to 5 years", " 6 to 10 years", " 11 to 15 years", " 16 to 20 years", " above 20 years"]',
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 2),
               array(
                    'id' => 8,
                    'name' => "What kind of cleansing materials are used",
                    'form_id' => 2,
                    'field_template_id' => 5,
                    'options' => '["disinfectants", " detergents", " locally made substances", " water only", " others"]',
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 3),

               array(
                    'id' => 9,
                    'name' => "Name",
                    'form_id' => 3,
                    'field_template_id' => 1,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 1),
               array(
                    'id' => 10,
                    'name' => "Birth Day",
                    'form_id' => 3,
                    'field_template_id' => 7,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 2),

               array(
                    'id' => 11,
                    'name' => "Major Subject",
                    'form_id' => 3,
                    'field_template_id' => 3,
                    'options' => '["History of Magic", "Muggle Studies", "Transfiguration", "Divination", "Potions"]',
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 3),
               array(
                    'id' => 12,
                    'name' => "Recording date",
                    'form_id' => 4,
                    'field_template_id' => 7,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 2),

               array(
                    'id' => 13,
                    'name' => "Subsidy Date",
                    'form_id' => 5,
                    'field_template_id' => 7,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 1),
               array(
                    'id' => 14,
                    'name' => "Amount",
                    'form_id' => 5,
                    'field_template_id' => 6,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 2),

               array(
                    'id' => 15,
                    'name' => "Award date",
                    'form_id' => 6,
                    'field_template_id' => 7,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 1),
               array(
                    'id' => 16,
                    'name' => "Amount",
                    'form_id' => 6,
                    'field_template_id' => 6,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 2),
               array(
                    'id' => 17,
                    'name' => "Paid?",
                    'form_id' => 6,
                    'field_template_id' => 5,
                    'options' => '["Yes", "No"]',
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 3),

               array(
                    'id' => 18,
                    'name' => "Ranker",
                    'form_id' => 7,
                    'field_template_id' => 1,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 1),
               array(
                    'id' => 19,
                    'name' => "SPPP",
                    'form_id' => 7,
                    'field_template_id' => 6,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 2),

               array(
                    'id' => 20,
                    'name' => "Groundbreaking Date",
                    'form_id' => 8,
                    'field_template_id' => 7,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 1),
               array(
                    'id' => 21,
                    'name' => "Source of funding",
                    'form_id' => 8,
                    'field_template_id' => 1,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 2),
               array(
                    'id' => 22,
                    'name' => "Source of funding",
                    'form_id' => 8,
                    'field_template_id' => 1,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 2),

               array(
                    'id' => 23,
                    'name' => "Sample TextArea",
                    'form_id' => 9,
                    'field_template_id' => 2,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 1),
               array(
                    'id' => 24,
                    'name' => "Sample CheckBox",
                    'form_id' => 9,
                    'field_template_id' => 4,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 2),
               array(
                    'id' => 25,
                    'name' => "Sample CheckBox Group",
                    'form_id' => 9,
                    'field_template_id' => 4,
                    'options' => '["Option1", "Option2", "Option3", "Option4", "Option5"]',
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 3),

               array(
                    'id' => 26,
                    'name' => "Sample TextArea",
                    'form_id' => 10,
                    'field_template_id' => 2,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 1),
               array(
                    'id' => 27,
                    'name' => "Sample CheckBox",
                    'form_id' => 10,
                    'field_template_id' => 4,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 2),
               array(
                    'id' => 28,
                    'name' => "Sample CheckBox Group",
                    'form_id' => 10,
                    'field_template_id' => 4,
                    'options' => '["Option1", "Option2", "Option3", "Option4", "Option5"]',
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 3),

               array(
                    'id' => 29,
                    'name' => "Recording Date",
                    'form_id' => 11,
                    'field_template_id' => 7,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 1),
               array(
                    'id' => 30,
                    'name' => "Speed Tracker",
                    'form_id' => 11,
                    'field_template_id' => 8,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 2),

               array(
                    'id' => 31,
                    'name' => "IRI Tracker",
                    'form_id' => 12,
                    'field_template_id' => 10,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 1),


               array(
                    'id' => 32,
                    'name' => "Unit Test TextBox",
                    'form_id' => 13,
                    'field_template_id' => 1,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 1),
               array(
                    'id' => 33,
                    'name' => "Unit Test TextArea",
                    'form_id' => 13,
                    'field_template_id' => 2,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 2),
               array(
                    'id' => 34,
                    'name' => "Unit Test DropDownList",
                    'form_id' => 13,
                    'field_template_id' => 3,
                    'options' => '["Option1", "Option2", "Option3"]',
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 3),
               array(
                    'id' => 35,
                    'name' => "Unit Test CheckBox",
                    'form_id' => 13,
                    'field_template_id' => 4,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 4),
               array(
                    'id' => 36,
                    'name' => "Unit Test RadioButton",
                    'form_id' => 13,
                    'field_template_id' => 5,
                    'options' => '["Option1", "Option2", "Option3"]',
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 5),
               array(
                    'id' => 37,
                    'name' => "Unit Test Numerical",
                    'form_id' => 13,
                    'field_template_id' => 6,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 6),
               array(
                    'id' => 38,
                    'name' => "Unit Test Date",
                    'form_id' => 13,
                    'field_template_id' => 7,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 7),
               array(
                    'id' => 39,
                    'name' => "Unit Test CheckBoxGroup",
                    'form_id' => 13,
                    'field_template_id' => 9,
                    'options' => '["Option1", "Option2", "Option3"]',
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 8),
               array(
                    'id' => 40,
                    'name' => "Number of SHS1",
                    'form_id' => 1,
                    'field_template_id' => 6,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 9),
               array(
                    'id' => 41,
                    'name' => "Number of SHS2",
                    'form_id' => 1,
                    'field_template_id' => 6,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 10),
               array(
                    'id' => 42,
                    'name' => "Number of SHS3",
                    'form_id' => 1,
                    'field_template_id' => 6,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 11),
               array(
                    'id' => 43,
                    'name' => "SHS1 + SHS2 + SHS3",
                    'form_id' => 1,
                    'field_template_id' => 6,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 12,
                    'formula' => "[40]+[41]+[42]"),
               array(
                    'id' => 44,
                    'name' => "SHS1 * SHS2 / SHS3",
                    'form_id' => 1,
                    'field_template_id' => 6,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 13,
                    'formula' => "[40]*[41]/[42]"),
               array(
                    'id' => 45,
                    'name' => "SHS1 - SHS2 * SHS3",
                    'form_id' => 1,
                    'field_template_id' => 6,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 14,
                    'formula' => "[40]-([41]*[42])"),
               array(
                    'id' => 46,
                    'name' => "SHS1 - (SHS2 + SHS3)",
                    'form_id' => 1,
                    'field_template_id' => 6,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 15,
                    'formula' => "[40]-([41]+[42])"),
               array(
                    'id' => 47,
                    'name' => "Weight",
                    'form_id' => 3,
                    'field_template_id' => 6,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 4),
               array(
                    'id' => 48,
                    'name' => "Grade",
                    'form_id' => 3,
                    'field_template_id' => 3,
                    'options' => '["SHS1","SHS2","SHS3"]',
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 4),
               array(
                    'id' => 49,
                    'name' => "Entering Year",
                    'form_id' => 3,
                    'field_template_id' => 3,
                    'options' => '["2010","2011","2012","2013","2014","2015","2016","2017"]',
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 5),
               array(
                    'id' => 50,
                    'name' => "Sex",
                    'form_id' => 3,
                    'field_template_id' => 3,
                    'options' => '["Male","Female"]',
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 6),
               array(
                    'id' => 51,
                    'name' => "Student ID",
                    'form_id' => 3,
                    'field_template_id' => 1,
                    'options' => null,
                    'view_level_id' => Config::get('argodf.default_perm.field.view'),
                    'edit_level_id' => Config::get('argodf.default_perm.field.edit'),
                    'order' => 7),
          );
          $this->command->info("FormField : Seeding " . count($records) . " records...");
          foreach ($records as $record) {
               DB::table('form_field')->insert($record);
          }
     }
}
